services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: gestionale_iliad_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: order_management
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./be/database/init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  # PHP Lumen Backend API
  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    container_name: gestionale_iliad_api
    restart: unless-stopped
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_HOST=mysql
      - DB_DATABASE=order_management
      - DB_USERNAME=app_user
      - DB_PASSWORD=app_password
    ports:
      - "8080:8000"
    extra_hosts:
      - "iliadApi:127.0.0.1"
    volumes:
      - ./be:/var/www/html
      - ./be/storage:/var/www/html/storage
    depends_on:
      - mysql
    networks:
      - app-network
    command: ["php", "-S", "0.0.0.0:8000", "-t", "public"]

  # Vue.js Frontend
  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    container_name: gestionale_iliad_frontend
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://iliadApi/api/v1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./fe:/app
      - /app/node_modules
      - /app/.vite
    depends_on:
      - backend
    networks:
      - app-network
    stdin_open: true
    tty: true

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: gestionale_iliad_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-network


volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
